import { isCloudinaryUrl } from "@/lib/cloudinary-url";

/**
 * Next.js Image loader for Cloudinary assets.
 *
 * Inserts responsive transformations (`f_auto,q_auto,w_…,c_fill`) directly
 * into the Cloudinary URL path so every size in the srcset is actually
 * generated by Cloudinary. Non-Cloudinary URLs pass through unchanged, which
 * keeps local/static media working during migration.
 */
export function cloudinaryImageLoader({ src, width, quality }: { src: string; width: number; quality?: number }) {
  if (!isCloudinaryUrl(src)) return src;
  let rest = src.split("/upload/")[1];
  if (!rest) return src;
  const segments = rest.split("/").filter(Boolean);
  if (/^v\d+$/.test(segments[0] ?? "")) segments.shift();
  const publicPath = segments.join("/");
  const transforms = [
    width && width > 0 ? `w_${Math.round(width)}` : "",
    "f_auto",
    quality ? `q_${Math.round(quality)}` : "q_auto",
    width && width > 0 ? "c_fill" : "",
  ]
    .filter(Boolean)
    .join(",");
  const base = src.split("/upload/")[0];
  return `${base}/upload/${transforms}/${publicPath}`;
}