import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader,CTASection } from "@/components/ui";
import { getClients,getProjects } from "@/lib/queries";
import SmartImage from "@/components/SmartImage";
export const metadata:Metadata={title:"HVAC Ducting Projects",description:"Explore verified MSNSS HVAC duct manufacturing, fabrication and installation projects by sector, region, year and status."};
export const dynamic="force-dynamic";
export default async function ProjectsPage({searchParams}:{searchParams:Promise<{status?:string;region?:string;sector?:string;year?:string}>}){const q=await searchParams,[all,clients]=await Promise.all([getProjects(),getClients()]);const projects=all.filter(p=>(!q.status||p.status===q.status)&&(!q.region||p.region===q.region)&&(!q.sector||p.category===q.sector)&&(!q.year||String(p.year)===q.year));const regions=[...new Set(all.map(p=>p.region).filter(Boolean))] as string[],sectors=[...new Set(all.map(p=>p.category))],years=[...new Set(all.map(p=>p.year).filter(Boolean))].sort((a,b)=>(b||0)-(a||0));const clientName=(id:number|null)=>clients.find(c=>c.id===id)?.name;
return <><PageHeader title="Our Projects" subtitle="Verified project experience across commercial, industrial and infrastructure environments." crumb="Projects"/><section className="bg-white py-16"><div className="mx-auto max-w-7xl px-6"><div className="mb-7 flex flex-wrap gap-2"><Link href="/projects" className="rounded-full border px-4 py-2 text-sm hover:border-brand">All Projects</Link>{["completed","ongoing","upcoming"].map(s=><Link key={s} href={`/projects?status=${s}`} className={`rounded-full px-4 py-2 text-sm capitalize ${q.status===s?"bg-brand text-white":"border"}`}>{s}</Link>)}</div><div id="sectors" className="mb-8 scroll-mt-28 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-3"><Filter label="Region" value={q.region} items={regions} parameter="region"/><Filter label="Sector" value={q.sector} items={sectors} parameter="sector"/><Filter label="Year" value={q.year} items={years.map(String)} parameter="year"/></div>{!projects.length?<div className="rounded-xl border border-dashed py-20 text-center"><div className="text-5xl">🏗️</div><h2 className="mt-4 text-xl font-bold">No published projects found</h2><p className="mt-2 text-slate-500">Verified projects matching this filter will appear here.</p></div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{projects.map(p=><Link key={p.id} href={`/projects/${p.slug}`} className="group overflow-hidden rounded-xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="zoom-frame relative h-52 overflow-hidden"><SmartImage src={p.imageUrl} alt={`${p.name} – MSNSS project`} fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover"/><span className="absolute right-3 top-3 rounded-full bg-brand px-3 py-1 text-xs font-semibold capitalize text-white">{p.status}</span></div><div className="p-5"><div className="text-xs font-semibold uppercase text-brand">{p.category}{p.region?` · ${p.region}`:""}</div><h2 className="mt-1 text-lg font-bold group-hover:text-brand">{p.name}</h2>{clientName(p.clientId)&&<p className="mt-1 text-sm font-medium">Client: {clientName(p.clientId)}</p>}<p className="mt-1 text-sm text-slate-500">{p.location}{p.year?` · ${p.year}`:""}</p><p className="mt-3 line-clamp-2 text-sm text-slate-600">{p.shortDescription||p.description}</p></div></Link>)}</div>}</div></section><CTASection/></>}
function Filter({label,value,items,parameter}:{label:string;value?:string;items:string[];parameter:string}){return <div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><div className="flex flex-wrap gap-1.5">{items.length?items.map(item=><Link key={item} href={`/projects?${parameter}=${encodeURIComponent(item)}`} className={`rounded-md px-2.5 py-1.5 text-xs ${value===item?"bg-slate-900 text-white":"bg-white text-slate-600 hover:text-brand"}`}>{item}</Link>):<span className="text-xs text-slate-400">No options</span>}</div></div>}
