import { db } from "@/db";
import { clients,projects } from "@/db/schema";
import { eq,sql } from "drizzle-orm";
import { requireAuth,slugify } from "@/lib/admin-api";
import { z } from "zod";
export const dynamic="force-dynamic";
const input=z.object({name:z.string().trim().min(2),slug:z.string().optional(),logoUrl:z.string().min(1),logoAlt:z.string().optional().nullable(),websiteUrl:z.string().optional().nullable(),industry:z.string().optional().nullable(),location:z.string().optional().nullable(),row:z.coerce.number().int().min(1).max(2),workSummary:z.string().trim().min(3),description:z.string().optional().nullable(),servicesProvided:z.array(z.string()).default([]),projectDetails:z.string().default(""),sortOrder:z.coerce.number().int().default(0),featured:z.boolean().default(false),active:z.boolean().default(true),showInLogoRow:z.boolean().default(true),logoRowOrder:z.coerce.number().int().default(0)});
export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){const unauth=await requireAuth();if(unauth)return unauth;try{const id=Number((await params).id);const parsed=input.safeParse(await req.json());if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message},{status:400});const b=parsed.data;const [row]=await db.update(clients).set({name:b.name,slug:slugify(b.slug||b.name),logoUrl:b.logoUrl,logoAlt:b.logoAlt||`${b.name} logo`,websiteUrl:b.websiteUrl||null,industry:b.industry||null,location:b.location||null,row:b.row,workSummary:b.workSummary,description:b.description||null,servicesProvided:b.servicesProvided,projectDetails:b.projectDetails,sortOrder:b.sortOrder,featured:b.featured,active:b.active,showInLogoRow:b.showInLogoRow,logoRowOrder:b.logoRowOrder,updatedAt:new Date()}).where(eq(clients.id,id)).returning();if(!row)return Response.json({error:"Client not found"},{status:404});return Response.json(row)}catch(e){console.error(e);return Response.json({error:"Unable to update client. Check that the slug is unique."},{status:500})}}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){const unauth=await requireAuth();if(unauth)return unauth;const id=Number((await params).id);const [count]=await db.select({value:sql<number>`count(*)::int`}).from(projects).where(eq(projects.clientId,id));if((count?.value||0)>0){await db.update(clients).set({active:false,updatedAt:new Date()}).where(eq(clients.id,id));return Response.json({ok:true,softDeleted:true,message:"Client was deactivated because it has associated projects."})}await db.delete(clients).where(eq(clients.id,id));return Response.json({ok:true,softDeleted:false})}
