import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader, CTASection } from "@/components/ui";
import { getProducts } from "@/lib/queries";
import SmartImage from "@/components/SmartImage";

export const revalidate = 300;
export const metadata:Metadata={title:"Plant & Machinery",description:"Inside the MSNSS manufacturing facility in Vasai: cutting, forming, welding, painting, storage and dispatch processes."};

const processes=["Plasma cutting","Flange cutting and hole pressing","Bending and punching","Gas welding","Spray painting","Fabrication","Finished duct storage","Loading and dispatch"];
export default async function PlantPage(){const machines=await getProducts("Plant and Machinery");return <><PageHeader title="Inside the MSNSS Manufacturing Facility" subtitle="Manufacturing is where quality begins." crumb="Plant & Machinery"/><section className="bg-white py-16"><div className="mx-auto max-w-7xl px-6"><div className="grid items-center gap-10 lg:grid-cols-2"><div><span className="text-sm font-bold uppercase tracking-wider text-brand">Manufacturing Capability</span><h2 className="mt-2 text-3xl font-extrabold">Built Around Accurate Fabrication</h2><p className="mt-4 leading-7 text-slate-600">Our Vasai facility supports cutting, forming, joining, finishing, storage and dispatch for project ducting requirements. Machine brands, models and capacities are published only when verified.</p><div className="mt-6 grid grid-cols-2 gap-3">{processes.map(p=><div key={p} className="border-l-2 border-brand pl-3 text-sm text-slate-600">{p}</div>)}</div></div><SmartImage src="/images/factory.jpg" alt="MSNSS manufacturing facility" width={1024} height={768} sizes="(max-width:1024px) 100vw, 50vw" className="min-h-80 w-full rounded-2xl object-cover shadow-lg"/></div><h2 className="mb-7 mt-16 text-3xl font-extrabold">Plant &amp; Machinery</h2>{machines.length?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{machines.map(m=><Link href={`/plant-and-machinery/${m.slug}`} key={m.id} className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm hover:border-brand hover:shadow-lg"><div className="zoom-frame relative h-52 w-full overflow-hidden"><SmartImage src={m.imageUrl} alt={`${m.name} at MSNSS manufacturing facility`} fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover"/></div><div className="p-5"><h3 className="text-lg font-bold group-hover:text-brand">{m.name}</h3><p className="mt-2 text-sm text-slate-600">{m.shortDescription}</p><span className="mt-4 inline-block text-sm font-semibold text-brand">View machine →</span></div></Link>)}</div>:<div className="rounded-xl border border-dashed p-12 text-center text-slate-500">Machinery records will appear here after publication.</div>}</div></section><CTASection/></>}
