import type { ProductContent } from "./types";

export const PRODUCTS_PART1: ProductContent[] = [
  {
    slug: "ms-rectangular-duct",
    name: "MS Rectangular Duct",
    h1: "MS Rectangular Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "MS Rectangular Duct",
    secondaryKeywords: [
      "MS Rectangular Duct Manufacturer in Mumbai",
      "MS ducting fabrication",
      "HVAC rectangular duct India",
      "mild steel duct supplier",
    ],
    seoTags: [
      "MS Rectangular Duct", "MS Duct Manufacturer", "HVAC Duct Mumbai",
      "Mild Steel Ducting", "Rectangular Duct Fabrication", "TDF Duct",
      "Flange Duct", "HVAC Ducting India", "Duct Fabrication", "Industrial Ducting",
    ],
    seoTitle: "MS Rectangular Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures and supplies MS Rectangular Ducts in customized sizes, gauges and jointing configurations. Drawing-based fabrication with pan-India supply. Get a quote.",
    seoKeywords:
      "MS rectangular duct, MS duct manufacturer Mumbai, mild steel HVAC duct, rectangular duct supplier India, TDF cleat flange duct",
    shortDescription:
      "Our **MS Rectangular Ducts** are precision-fabricated mild steel HVAC ducts designed for efficient air distribution across commercial, industrial, and infrastructure projects. As an **MS Rectangular Duct Manufacturer in Mumbai**, we provide complete **duct design, fabrication, supply and installation support across India**.\n\nManufactured from quality mild steel sheets, our rectangular ducts are engineered according to approved drawings, project requirements and applicable HVAC ducting standards. Each duct is accurately cut, formed, reinforced and joined to provide reliable performance, structural strength and long service life.\n\nWe manufacture and supply **MS Rectangular HVAC Ducts in customized sizes, gauges and jointing configurations** for new HVAC installations, industrial ventilation systems, commercial buildings and large-scale infrastructure projects.",
    manufacturingNarrative:
      "### Precision MS Rectangular Duct Manufacturing\n\nOur ducts are manufactured using controlled fabrication processes to achieve accurate dimensions, proper joint alignment and a good fit during site installation. Depending on project requirements, ducts can be manufactured with **TDF, Cleat or Flange-type joints**.\n\nWe can manufacture ducts as per approved shop drawings and project specifications, including customized dimensions, thickness, reinforcement and configuration.",
    material:
      "Quality mild steel (MS) sheet, in the gauge range appropriate to duct size and project requirement.",
    technicalSpecifications: [
      { label: "Product", value: "MS Rectangular Duct" },
      { label: "Material", value: "Mild Steel (MS)" },
      { label: "Gauge Range", value: "18G to 24G" },
      { label: "Thickness", value: "As per gauge and project requirement" },
      { label: "Standards", value: "SMACNA / DW 144" },
      { label: "Jointing Options", value: "TDF / Cleat / Flange" },
      { label: "Size", value: "Standard & Custom Sizes" },
      { label: "Fabrication", value: "As per Approved Drawings" },
      { label: "Application", value: "HVAC Air Distribution & Industrial Ventilation" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available on Order" },
    ],
    features: [
      "Strong mild steel construction",
      "Suitable for high-volume air distribution",
      "Precision fabrication as per approved drawings",
      "TDF, Cleat and Flange jointing options",
      "Customized dimensions available",
      "Suitable for commercial and industrial HVAC systems",
      "Designed for reliable long-term performance",
      "Suitable for large-scale HVAC projects",
      "Professional fabrication and finishing",
      "Design, manufacturing and supply support across India",
    ],
    benefits: [
      "Experienced HVAC duct fabrication",
      "Quality mild steel material",
      "Customized manufacturing",
      "Drawing-based fabrication",
      "Multiple jointing options",
      "Commercial & industrial applications",
      "Project-oriented production",
      "Pan-India supply",
      "Suitable for new HVAC installations and expansion projects",
    ],
    applicationDetails: [
      { title: "Commercial Buildings", description: "Used for centralized HVAC air distribution in offices, commercial complexes and corporate buildings." },
      { title: "Industrial Plants", description: "Suitable for industrial ventilation, process areas and large-volume air movement requirements." },
      { title: "Hospitals & Clean Rooms", description: "Can be fabricated according to project-specific HVAC requirements for controlled environments." },
      { title: "Malls & Retail Spaces", description: "Suitable for distributing conditioned air throughout shopping malls, retail buildings and large commercial spaces." },
      { title: "Warehouses", description: "Used for ventilation and HVAC air distribution in warehouses, logistics facilities and storage buildings." },
      { title: "Hotels & Hospitality", description: "Suitable for centralized air-conditioning and ventilation systems in hotels, resorts and hospitality projects." },
      { title: "Infrastructure Projects", description: "Designed and fabricated for HVAC applications in large infrastructure and institutional projects." },
    ],
    designFabrication:
      "Our **MS Rectangular Duct design and fabrication** process can be carried out according to approved HVAC drawings and site requirements. We can support projects with customized duct dimensions, jointing systems, gauge selection and fabrication requirements.\n\nOur team focuses on accurate fabrication to simplify transportation, site installation and duct assembly.",
    supplyAcrossIndia:
      "We provide **MS Rectangular Duct manufacturing and supply across India**, supporting HVAC contractors, consultants, EPC companies, industrial clients, commercial projects and infrastructure developers.\n\nFrom **duct design and fabrication to bulk supply**, our solutions can be customized according to project requirements and delivery schedules.",
    faqs: [
      { question: "What is an MS Rectangular Duct?", answer: "An MS Rectangular Duct is a rectangular HVAC air duct fabricated from mild steel sheets and used for transporting and distributing conditioned or ventilated air through commercial, industrial and infrastructure buildings." },
      { question: "What gauges are available for MS Rectangular Ducts?", answer: "Our MS rectangular ducts can be fabricated in **18G to 24G**, depending on duct size, application and project requirements." },
      { question: "Do you manufacture customized MS Rectangular Ducts?", answer: "Yes. **Custom-size MS rectangular ducts** can be manufactured according to approved drawings and specific project requirements." },
      { question: "Which jointing systems are available?", answer: "Depending on the project requirement, ducts can be fabricated with **TDF, Cleat or Flange jointing systems**." },
      { question: "Do you supply MS Rectangular Ducts outside Mumbai?", answer: "Yes. We provide **MS Rectangular Duct design, manufacturing and supply across India**, with project-specific support for customers outside Mumbai." },
      { question: "Are the ducts suitable for industrial HVAC applications?", answer: "Yes. MS rectangular ducts are suitable for a wide range of **industrial HVAC, ventilation and air-distribution applications**, subject to the project design and specification." },
    ],
    manufacturingProcess: [
      "Drawing review and material planning",
      "Accurate sheet cutting to required dimensions",
      "Forming, folding and edge preparation",
      "Reinforcement and flange / cleat / TDF formation",
      "Jointing, finishing and dimensional inspection",
      "Marking, protection and dispatch preparation",
    ],
    installationInformation: [
      "Fabricated to approved shop drawings for accurate site fit",
      "Section identification and marking for sequential assembly",
      "Jointing arrangement as selected for the project",
      "Coordination with supports, hangers and services",
    ],
    maintenanceInformation: [
      "Periodic inspection of joints and external surfaces",
      "Cleaning access as provided by the system design",
      "Touch-up of damaged protective finish where applicable",
      "Re-tightening of accessible flange fasteners as required",
    ],
    industries: ["Commercial", "Industrial", "Healthcare", "Retail", "Logistics", "Hospitality", "Infrastructure"],
  },

  {
    slug: "ss-rectangular-duct",
    name: "SS Rectangular Duct",
    h1: "SS Rectangular Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "SS Rectangular Duct",
    secondaryKeywords: [
      "SS Rectangular Duct Manufacturer in Mumbai",
      "stainless steel HVAC duct",
      "SS ducting fabrication",
      "hygienic duct supplier",
    ],
    seoTags: [
      "SS Rectangular Duct", "Stainless Steel Duct", "SS Duct Manufacturer",
      "HVAC Duct Mumbai", "Kitchen Exhaust Duct", "Hygienic Ducting",
      "SS 304 Duct", "Duct Fabrication India", "Ventilation Duct", "Exhaust Duct",
    ],
    seoTitle: "SS Rectangular Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS fabricates SS Rectangular Ducts in customized sizes, thicknesses and jointing configurations for HVAC, ventilation and exhaust. Drawing-based supply across India.",
    seoKeywords:
      "SS rectangular duct, stainless steel duct manufacturer Mumbai, SS HVAC duct, SS ducting supplier India, hygienic ducting",
    shortDescription:
      "Our **SS Rectangular Ducts** are precision-fabricated stainless steel HVAC ducts designed for efficient air distribution, ventilation and exhaust applications across commercial, industrial and specialized projects. As an **SS Rectangular Duct Manufacturer in Mumbai**, we provide customized duct fabrication and supply according to project requirements.\n\nManufactured using suitable stainless steel sheets, our rectangular ducts are fabricated according to approved drawings, required dimensions and application-specific specifications. Stainless steel construction provides a durable ducting solution for applications where cleanliness, corrosion resistance and long-term performance are important.\n\nWe manufacture and supply **SS Rectangular HVAC Ducts in customized sizes, thicknesses and jointing configurations** for HVAC systems, industrial ventilation, commercial buildings, kitchens and specialized environments.",
    manufacturingNarrative:
      "### Precision SS Rectangular Duct Manufacturing\n\nOur stainless steel ducts are accurately cut, formed, reinforced and assembled to achieve proper dimensions and joint alignment. Duct construction can be customized according to project drawings and installation requirements.\n\nDepending on the application, suitable **TDF, Cleat, Flange or other approved jointing arrangements** can be provided.",
    material:
      "Stainless steel sheet, in the grade and thickness specified for the project and application.",
    technicalSpecifications: [
      { label: "Product", value: "SS Rectangular Duct" },
      { label: "Material", value: "Stainless Steel" },
      { label: "Material Grade", value: "As per Project Requirement" },
      { label: "Thickness", value: "As per Application & Drawing" },
      { label: "Jointing Options", value: "TDF / Cleat / Flange / As Specified" },
      { label: "Size", value: "Standard & Custom Sizes" },
      { label: "Fabrication", value: "As per Approved Drawings" },
      { label: "Application", value: "HVAC / Ventilation / Exhaust" },
      { label: "Finish", value: "As Required" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available on Order" },
    ],
    features: [
      "Stainless steel construction",
      "Corrosion-resistant material options",
      "Accurate dimensional fabrication",
      "Customized sizes and configurations",
      "Suitable for ventilation and exhaust applications",
      "Suitable for commercial and industrial HVAC systems",
      "Clean and professional fabrication",
      "Drawing-based manufacturing",
      "Multiple jointing options",
      "Pan-India supply",
    ],
    benefits: [
      "Stainless steel fabrication",
      "Customized manufacturing",
      "Drawing-based production",
      "Accurate dimensions",
      "Suitable for HVAC and ventilation",
      "Commercial and industrial applications",
      "Project-specific fabrication",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Commercial HVAC Systems", description: "Used for air distribution and ventilation in commercial buildings and large facilities." },
      { title: "Industrial Plants", description: "Suitable for industrial ventilation and exhaust applications where durable duct construction is required." },
      { title: "Commercial Kitchens", description: "Suitable for ventilation and exhaust systems in restaurants, hotels and commercial kitchens." },
      { title: "Food Processing Facilities", description: "Stainless steel ducting can be considered for applications where hygiene and corrosion resistance are important." },
      { title: "Hospitals & Specialized Facilities", description: "Can be fabricated according to project-specific HVAC and ventilation requirements." },
      { title: "Hotels & Hospitality", description: "Suitable for HVAC, kitchen exhaust and ventilation installations." },
      { title: "Industrial Ventilation", description: "Used for controlled movement of air, ventilation and exhaust within industrial environments." },
    ],
    designFabrication:
      "Our **SS Rectangular Duct design and fabrication** is carried out according to approved drawings and application requirements. Dimensions, thickness, material grade, reinforcement and jointing configuration can be selected according to project specifications.",
    supplyAcrossIndia:
      "We supply **SS Rectangular Ducts across India** for HVAC contractors, EPC companies, industrial clients, consultants and commercial projects.",
    faqs: [
      { question: "What is an SS Rectangular Duct?", answer: "An SS Rectangular Duct is a rectangular HVAC or ventilation duct fabricated from stainless steel sheets for transporting air, ventilation or exhaust." },
      { question: "Can SS Rectangular Ducts be customized?", answer: "Yes. Dimensions, thickness, material grade and jointing configuration can be customized according to approved project drawings." },
      { question: "Where are SS Rectangular Ducts used?", answer: "They are commonly used in HVAC systems, industrial ventilation, commercial kitchens, exhaust systems and applications requiring durable stainless steel construction." },
      { question: "Do you supply SS Rectangular Ducts outside Mumbai?", answer: "Yes. We provide SS Rectangular Duct manufacturing and supply across India." },
    ],
    manufacturingProcess: [
      "Drawing review and grade selection",
      "Accurate cutting of stainless steel sheet",
      "Forming and edge preparation",
      "Reinforcement and joint configuration",
      "Assembly, finishing and inspection",
      "Protection, marking and dispatch",
    ],
    installationInformation: [
      "Fabricated to approved drawings for accurate assembly",
      "Handling and storage to preserve surface finish",
      "Jointing arrangement as specified for the application",
      "Coordination with hangers and building services",
    ],
    maintenanceInformation: [
      "Routine cleaning to maintain surface hygiene",
      "Inspection of joints and external finish",
      "Use of compatible cleaning agents for stainless steel",
      "Periodic checks at maintenance access points",
    ],
    industries: ["Commercial", "Industrial", "Healthcare", "Hospitality", "Food Processing"],
  },

  {
    slug: "ms-round-duct",
    name: "MS Round Duct",
    h1: "MS Round Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "MS Round Duct",
    secondaryKeywords: [
      "MS Round Duct Manufacturer in Mumbai",
      "circular mild steel duct",
      "spiral duct supplier",
      "HVAC round ducting India",
    ],
    seoTags: [
      "MS Round Duct", "Circular Duct", "Round Duct Manufacturer", "Mild Steel Duct",
      "HVAC Duct Mumbai", "Ventilation Duct", "Exhaust Duct", "Spiral Duct",
      "Duct Fabrication India", "Industrial Ducting",
    ],
    seoTitle: "MS Round Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures MS Round Ducts in standard and custom diameters for HVAC, ventilation and exhaust. Drawing-based fabrication with pan-India supply.",
    seoKeywords:
      "MS round duct, circular mild steel duct, round duct manufacturer Mumbai, HVAC round ducting India, ventilation duct supplier",
    shortDescription:
      "Our **MS Round Ducts** are precision-fabricated mild steel circular ducts designed for HVAC air distribution, ventilation and exhaust applications. As an **MS Round Duct Manufacturer in Mumbai**, we manufacture and supply customized round ducts for commercial, industrial and infrastructure projects.\n\nManufactured from quality mild steel sheets, our round ducts are produced according to required diameters, thicknesses, lengths and project specifications. Circular duct construction provides an efficient option for various air movement and ventilation applications.",
    manufacturingNarrative:
      "### Precision MS Round Duct Manufacturing\n\nOur ducts are fabricated using controlled sheet-metal processes to achieve accurate circular dimensions and proper connections. Duct dimensions and configurations can be manufactured according to approved drawings.",
    material: "Quality mild steel (MS) sheet, in the thickness appropriate to diameter and project requirement.",
    technicalSpecifications: [
      { label: "Product", value: "MS Round Duct" },
      { label: "Material", value: "Mild Steel" },
      { label: "Shape", value: "Circular / Round" },
      { label: "Diameter", value: "Standard & Custom" },
      { label: "Thickness", value: "As per Project Requirement" },
      { label: "Jointing", value: "As Specified" },
      { label: "Fabrication", value: "Drawing-Based" },
      { label: "Application", value: "HVAC / Ventilation / Exhaust" },
      { label: "Finish", value: "As Required" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Mild steel construction",
      "Circular duct design",
      "Customized diameters available",
      "Accurate fabrication",
      "Suitable for HVAC systems",
      "Suitable for ventilation and exhaust",
      "Project-specific manufacturing",
      "Easy integration with compatible duct components",
      "Commercial and industrial applications",
      "Pan-India supply",
    ],
    benefits: [
      "Precision sheet-metal fabrication",
      "Customized dimensions",
      "Drawing-based production",
      "Suitable for HVAC and ventilation",
      "Industrial and commercial applications",
      "Project-specific manufacturing",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "HVAC Air Distribution", description: "Used for transporting conditioned air through commercial and industrial HVAC systems." },
      { title: "Industrial Ventilation", description: "Suitable for ventilation and air movement in industrial facilities." },
      { title: "Exhaust Systems", description: "Can be used for suitable exhaust applications according to system design." },
      { title: "Warehouses & Industrial Buildings", description: "Suitable for large-area ventilation requirements." },
      { title: "Commercial Buildings", description: "Used in HVAC and ventilation installations across offices, commercial buildings and institutions." },
    ],
    designFabrication:
      "Our round ducts can be manufactured according to project drawings, required diameter, thickness, length and connection requirements.",
    supplyAcrossIndia:
      "We provide customized **MS Round Duct manufacturing and supply across India** for HVAC contractors, consultants, EPC companies and industrial customers.",
    faqs: [
      { question: "What is an MS Round Duct?", answer: "An MS Round Duct is a circular air duct manufactured from mild steel sheets and used for HVAC air distribution, ventilation and exhaust applications." },
      { question: "Can round duct diameter be customized?", answer: "Yes. Round ducts can be manufactured in customized diameters according to project requirements." },
      { question: "Where are MS Round Ducts used?", answer: "They are used in HVAC systems, industrial ventilation, commercial buildings, warehouses and suitable exhaust applications." },
      { question: "Do you supply MS Round Ducts across India?", answer: "Yes. MSNSS provides manufacturing and supply support across India." },
    ],
    manufacturingProcess: [
      "Diameter and thickness confirmation against drawings",
      "Sheet cutting and rolling / spiral forming",
      "Seam joining and end preparation",
      "Connection and joint configuration",
      "Finishing and dimensional inspection",
      "Protection, marking and dispatch",
    ],
    installationInformation: [
      "Section lengths prepared for practical site handling",
      "Connections arranged as specified for the system",
      "Support spacing to suit diameter and project requirements",
      "Alignment checks during installation",
    ],
    maintenanceInformation: [
      "Periodic inspection of seams and connections",
      "Cleaning where the application requires it",
      "External protective finish upkeep",
      "Inspection at designated access points",
    ],
    industries: ["Commercial", "Industrial", "Logistics", "Infrastructure"],
  },

  {
    slug: "ss-round-duct",
    name: "SS Round Duct",
    h1: "SS Round Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "SS Round Duct",
    secondaryKeywords: [
      "SS Round Duct Manufacturer in Mumbai",
      "stainless steel circular duct",
      "SS exhaust ducting",
      "hygienic round duct",
    ],
    seoTags: [
      "SS Round Duct", "Stainless Steel Round Duct", "Circular SS Duct",
      "SS Duct Manufacturer", "Kitchen Exhaust Duct", "Industrial Exhaust Duct",
      "Corrosion Resistant Duct", "HVAC Duct Mumbai", "Duct Fabrication India",
    ],
    seoTitle: "SS Round Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS fabricates SS Round Ducts in custom diameters and grades for HVAC, ventilation and exhaust applications. Drawing-based manufacturing and pan-India supply.",
    seoKeywords:
      "SS round duct, stainless steel round duct, SS circular duct manufacturer Mumbai, SS exhaust ducting India",
    shortDescription:
      "Our **SS Round Ducts** are stainless steel circular ducts designed for HVAC, ventilation and exhaust applications requiring durable and corrosion-resistant duct construction. As an **SS Round Duct Manufacturer in Mumbai**, we provide customized fabrication and supply for commercial and industrial projects.",
    manufacturingNarrative:
      "### Precision SS Round Duct Manufacturing\n\nSS round ducts are accurately fabricated according to required diameter, thickness, material grade and project specifications. Customized lengths and connection arrangements can also be provided according to approved drawings.",
    material: "Stainless steel sheet, in the grade and thickness specified for the application.",
    technicalSpecifications: [
      { label: "Product", value: "SS Round Duct" },
      { label: "Material", value: "Stainless Steel" },
      { label: "Shape", value: "Circular" },
      { label: "Material Grade", value: "As Per Requirement" },
      { label: "Diameter", value: "Standard & Custom" },
      { label: "Thickness", value: "As Per Application" },
      { label: "Jointing", value: "As Specified" },
      { label: "Fabrication", value: "Approved Drawings" },
      { label: "Application", value: "HVAC / Ventilation / Exhaust" },
      { label: "Supply", value: "Pan India" },
    ],
    features: [
      "Stainless steel construction",
      "Corrosion-resistant material options",
      "Customized diameter",
      "Accurate circular fabrication",
      "Suitable for ventilation and exhaust",
      "Suitable for HVAC systems",
      "Project-specific manufacturing",
      "Professional finish",
      "Pan-India supply",
    ],
    benefits: [
      "Stainless steel construction",
      "Customized fabrication",
      "Drawing-based production",
      "Accurate dimensions",
      "HVAC and ventilation applications",
      "Industrial applications",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Industrial Ventilation", description: "Used for controlled air movement and ventilation in industrial environments." },
      { title: "Commercial HVAC", description: "Suitable for round duct runs in commercial air-conditioning and ventilation systems." },
      { title: "Kitchen Exhaust", description: "Suitable for exhaust applications in restaurants, hotels and commercial kitchens." },
      { title: "Industrial Exhaust", description: "Used for exhaust duties where corrosion-resistant duct construction is required." },
      { title: "Hotels & Hospitality", description: "Suitable for HVAC and exhaust installations in hospitality facilities." },
      { title: "Food-Processing Environments", description: "Can be considered where stainless steel construction is specified." },
      { title: "Commercial Buildings", description: "Used across offices, institutions and commercial developments." },
      { title: "Specialized Ventilation Systems", description: "Fabricated to suit project-specific ventilation arrangements." },
    ],
    designFabrication:
      "Our fabrication process allows customization of diameter, thickness, material grade, length and connection configuration based on project drawings.",
    supplyAcrossIndia:
      "We manufacture and supply SS Round Ducts across India for HVAC contractors, industrial clients, EPC companies and commercial projects.",
    faqs: [
      { question: "What is an SS Round Duct?", answer: "An SS Round Duct is a circular duct fabricated from stainless steel sheets for air distribution, ventilation and exhaust applications." },
      { question: "Can SS Round Ducts be customized?", answer: "Yes. Diameter, thickness, material grade and configuration can be customized." },
      { question: "Where are SS Round Ducts used?", answer: "They can be used in HVAC, industrial ventilation, exhaust, commercial kitchen and specialized ventilation systems." },
    ],
    manufacturingProcess: [
      "Grade and thickness confirmation",
      "Sheet cutting and circular forming",
      "Seam joining and finishing",
      "Connection arrangement as specified",
      "Dimensional inspection",
      "Protection, marking and dispatch",
    ],
    installationInformation: [
      "Lengths prepared for practical site handling",
      "Connections configured to suit the system",
      "Support arrangement as per project requirements",
      "Handling to preserve surface finish",
    ],
    maintenanceInformation: [
      "Periodic inspection of seams and joints",
      "Cleaning using compatible agents",
      "Surface finish upkeep",
      "Inspection at access points",
    ],
    industries: ["Commercial", "Industrial", "Hospitality", "Food Processing"],
  },

  {
    slug: "angle-frame-duct",
    name: "Angle Frame Duct",
    h1: "Angle Frame Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "Angle Frame Duct",
    secondaryKeywords: [
      "Angle Frame Duct Manufacturer in Mumbai",
      "reinforced HVAC duct",
      "heavy duty ducting",
      "industrial duct fabrication",
    ],
    seoTags: [
      "Angle Frame Duct", "Reinforced Duct", "Heavy Duty Ducting", "HVAC Duct Mumbai",
      "Industrial Ducting", "Large Duct Section", "Duct Fabrication India",
      "Structural Angle Duct", "Ventilation Duct",
    ],
    seoTitle: "Angle Frame Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures Angle Frame Ducts with structural angle reinforcement for larger duct sections. Customized drawing-based fabrication with pan-India supply.",
    seoKeywords:
      "angle frame duct, reinforced HVAC duct, heavy duty duct manufacturer Mumbai, industrial ducting India",
    shortDescription:
      "Our **Angle Frame Ducts** are robust HVAC ducting systems fabricated with structural angle-frame reinforcement for applications requiring additional rigidity and strength. As an **Angle Frame Duct Manufacturer in Mumbai**, we manufacture customized ducts according to project drawings and HVAC specifications.\n\nAngle-frame construction can provide additional structural support for larger duct sections and demanding installations.",
    manufacturingNarrative:
      "### Precision Angle Frame Duct Manufacturing\n\nThe duct body and supporting angle-frame structure are fabricated and assembled according to approved drawings. Dimensions, sheet thickness, reinforcement and frame configuration can be customized according to project requirements.",
    material: "Sheet metal duct construction with structural angle-frame reinforcement, selected to suit the project requirement.",
    technicalSpecifications: [
      { label: "Product", value: "Angle Frame Duct" },
      { label: "Construction", value: "Sheet Metal with Angle Frame" },
      { label: "Material", value: "As Per Project Requirement" },
      { label: "Frame", value: "Structural Angle" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Thickness", value: "As Per Drawing" },
      { label: "Jointing", value: "Flange / As Specified" },
      { label: "Fabrication", value: "Approved Drawings" },
      { label: "Application", value: "HVAC / Ventilation" },
      { label: "Supply", value: "Pan India" },
    ],
    features: [
      "Strong angle-frame construction",
      "Suitable for larger duct sections",
      "Customized dimensions",
      "Drawing-based fabrication",
      "Reinforced duct structure",
      "Suitable for industrial applications",
      "Suitable for commercial HVAC",
      "Project-specific manufacturing",
      "Professional fabrication",
      "Pan-India supply",
    ],
    benefits: [
      "Reinforced construction",
      "Customized fabrication",
      "Drawing-based manufacturing",
      "Suitable for large duct sections",
      "Industrial HVAC applications",
      "Project-specific production",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Industrial HVAC Systems", description: "Used in industrial facilities where duct sections require additional structural support." },
      { title: "Large Commercial Buildings", description: "Suitable for larger air-distribution duct runs in commercial developments." },
      { title: "Manufacturing Plants", description: "Used for ventilation and air-handling ductwork within production facilities." },
      { title: "Industrial Ventilation", description: "Suitable for demanding ventilation duties and larger duct configurations." },
      { title: "Infrastructure Projects", description: "Fabricated for HVAC applications in large infrastructure and institutional projects." },
      { title: "Large Air-Distribution Systems", description: "Angle-frame construction supports larger section sizes used in high-volume systems." },
      { title: "Warehouses", description: "Suitable for ventilation ductwork in warehouses and logistics facilities." },
      { title: "Utility & Service Areas", description: "Used in plant rooms, service zones and utility areas." },
    ],
    designFabrication:
      "Our team can manufacture angle-frame ducts according to approved HVAC drawings, including duct dimensions, sheet thickness, reinforcement and frame requirements.",
    supplyAcrossIndia:
      "We provide **Angle Frame Duct manufacturing and supply across India** for industrial and commercial HVAC projects.",
    faqs: [
      { question: "What is an Angle Frame Duct?", answer: "An Angle Frame Duct is an HVAC duct reinforced using structural angle frames to provide additional rigidity and support." },
      { question: "Where are Angle Frame Ducts used?", answer: "They are commonly considered for larger duct sections and industrial or commercial HVAC installations where additional structural reinforcement is required." },
      { question: "Can the frame be customized?", answer: "Yes. Frame size, duct dimensions and reinforcement can be manufactured according to project requirements." },
    ],
    manufacturingProcess: [
      "Drawing review and structural requirement assessment",
      "Duct body cutting and forming",
      "Angle frame preparation and assembly",
      "Reinforcement and joint configuration",
      "Dimensional verification",
      "Finishing, marking and dispatch",
    ],
    installationInformation: [
      "Frame and duct sections prepared for site assembly",
      "Support arrangement to suit reinforced construction",
      "Jointing as specified for the project",
      "Coordination with structural and building services",
    ],
    maintenanceInformation: [
      "Inspection of frame connections and duct surfaces",
      "Re-tightening of accessible fasteners as required",
      "Protective finish upkeep",
      "Periodic checks at access locations",
    ],
    industries: ["Industrial", "Commercial", "Infrastructure", "Logistics"],
  },

  {
    slug: "flanged-duct",
    name: "Flanged Duct",
    h1: "Flanged Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "Flanged Duct",
    secondaryKeywords: [
      "Flanged Duct Manufacturer in Mumbai",
      "flange joint ducting",
      "HVAC duct with flanges",
      "duct assembly system",
    ],
    seoTags: [
      "Flanged Duct", "Flange Ducting", "HVAC Duct Mumbai", "Duct Jointing",
      "Duct Fabrication India", "Commercial Ducting", "Industrial Ventilation",
      "Duct Installation", "Custom Duct",
    ],
    seoTitle: "Flanged Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures Flanged Ducts with flange-type connections for secure duct assembly. Customized sizes and configurations with pan-India supply.",
    seoKeywords:
      "flanged duct, flange joint ducting, HVAC flanged duct manufacturer Mumbai, duct assembly India",
    shortDescription:
      "Our **Flanged Ducts** are precision-fabricated HVAC ducts designed with flange-type connections for secure duct assembly and installation. As a **Flanged Duct Manufacturer in Mumbai**, we manufacture and supply customized ducting systems for commercial, industrial and infrastructure HVAC projects.",
    manufacturingNarrative:
      "### Precision Flanged Duct Manufacturing\n\nDuct sections are fabricated according to approved drawings with flange connections suitable for the required installation and jointing arrangement.",
    material: "Mild steel or stainless steel as required by the project, in the specified thickness and flange configuration.",
    technicalSpecifications: [
      { label: "Product", value: "Flanged Duct" },
      { label: "Material", value: "MS / SS as Required" },
      { label: "Shape", value: "Rectangular / As Specified" },
      { label: "Jointing", value: "Flange Type" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Thickness", value: "As Per Drawing" },
      { label: "Fabrication", value: "Approved Drawings" },
      { label: "Application", value: "HVAC / Ventilation" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Flange-type duct connections",
      "Accurate fabrication",
      "Secure section joining",
      "Customized dimensions",
      "Suitable for commercial HVAC",
      "Suitable for industrial ventilation",
      "Drawing-based production",
      "Project-specific configuration",
      "Professional fabrication",
      "Pan-India supply",
    ],
    benefits: [
      "Accurate flange fabrication",
      "Customized dimensions",
      "Drawing-based production",
      "Suitable for industrial HVAC",
      "Commercial applications",
      "Project-oriented manufacturing",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Industrial HVAC", description: "Used in industrial air-distribution and ventilation systems requiring secure section joining." },
      { title: "Commercial Buildings", description: "Suitable for HVAC ductwork in offices, commercial complexes and institutions." },
      { title: "Manufacturing Facilities", description: "Used for ventilation and air-handling duct runs in production facilities." },
      { title: "Warehouses", description: "Suitable for large-area ducting installations in warehouses and logistics facilities." },
      { title: "Hospitals", description: "Can be fabricated to suit project-specific HVAC requirements in healthcare facilities." },
      { title: "Hotels", description: "Suitable for centralized HVAC and ventilation ducting in hospitality projects." },
      { title: "Infrastructure Projects", description: "Fabricated for HVAC applications in large infrastructure developments." },
      { title: "Ventilation Systems", description: "Used across a range of general ventilation and air-distribution duties." },
    ],
    designFabrication:
      "We manufacture flanged ducts according to approved shop drawings and project requirements, including dimensions, material, thickness and flange configuration.",
    supplyAcrossIndia:
      "Our flanged ducting solutions are available for HVAC contractors, EPC companies, consultants and industrial customers across India.",
    faqs: [
      { question: "What is a Flanged Duct?", answer: "A Flanged Duct is an HVAC duct section designed with flange connections for joining individual duct sections during installation." },
      { question: "Can flanged ducts be customized?", answer: "Yes. Duct size, material, thickness and flange configuration can be customized." },
      { question: "Where are flanged ducts used?", answer: "They are suitable for commercial HVAC, industrial ventilation and large ducting installations." },
    ],
    manufacturingProcess: [
      "Drawing and flange configuration review",
      "Sheet cutting and duct forming",
      "Flange formation and alignment",
      "Joint preparation and assembly",
      "Dimensional and fit verification",
      "Finishing, marking and dispatch",
    ],
    installationInformation: [
      "Sections marked for sequential site assembly",
      "Flange alignment checked before fastening",
      "Joint sealing arrangement as specified",
      "Support spacing to suit project requirements",
    ],
    maintenanceInformation: [
      "Periodic inspection of flange joints",
      "Re-tightening of accessible fasteners as required",
      "Inspection of joint sealing condition",
      "Surface finish upkeep",
    ],
    industries: ["Commercial", "Industrial", "Healthcare", "Hospitality", "Infrastructure"],
  },

  {
    slug: "kitchen-exhaust-duct",
    name: "Kitchen Exhaust Duct",
    h1: "Kitchen Exhaust Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "Kitchen Exhaust Duct",
    secondaryKeywords: [
      "Kitchen Exhaust Duct Manufacturer in Mumbai",
      "commercial kitchen ducting",
      "grease duct supplier",
      "restaurant exhaust duct",
    ],
    seoTags: [
      "Kitchen Exhaust Duct", "Commercial Kitchen Ducting", "Exhaust Duct Mumbai",
      "Restaurant Ducting", "Hotel Kitchen Exhaust", "Grease Duct",
      "Ventilation Duct India", "Food Facility Ducting", "Industrial Canteen Duct",
    ],
    seoTitle: "Kitchen Exhaust Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS fabricates Kitchen Exhaust Ducts for restaurants, hotels and commercial kitchens. Customized dimensions, material and configuration with pan-India supply.",
    seoKeywords:
      "kitchen exhaust duct, commercial kitchen ducting, restaurant exhaust duct manufacturer Mumbai, hotel kitchen duct India",
    shortDescription:
      "Our **Kitchen Exhaust Ducts** are fabricated for the efficient removal of heat, smoke, vapours and cooking exhaust from commercial and industrial kitchen environments. As a **Kitchen Exhaust Duct Manufacturer in Mumbai**, we provide customized duct fabrication and supply for restaurants, hotels, food facilities and commercial kitchens.\n\nKitchen exhaust ducting is designed according to the required airflow, route, dimensions, material and project specifications.",
    manufacturingNarrative:
      "### Precision Kitchen Exhaust Duct Manufacturing\n\nOur kitchen exhaust ducts are fabricated according to approved drawings and site requirements. Duct dimensions, material, thickness, jointing and access requirements can be customized according to the application.",
    material: "Selected to suit the application and project specification, with thickness and construction appropriate to the exhaust duty.",
    technicalSpecifications: [
      { label: "Product", value: "Kitchen Exhaust Duct" },
      { label: "Material", value: "As Per Project Requirement" },
      { label: "Shape", value: "Rectangular / Round" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Thickness", value: "As Per Design" },
      { label: "Jointing", value: "As Specified" },
      { label: "Fabrication", value: "Approved Drawings" },
      { label: "Application", value: "Kitchen Exhaust & Ventilation" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Designed for kitchen exhaust systems",
      "Customized dimensions",
      "Suitable for commercial kitchens",
      "Suitable for restaurants and hotels",
      "Accurate fabrication",
      "Drawing-based production",
      "Suitable for heat and vapour exhaust applications",
      "Project-specific configuration",
      "Professional fabrication",
      "Pan-India supply",
    ],
    benefits: [
      "Application-specific fabrication",
      "Customized dimensions",
      "Drawing-based production",
      "Commercial kitchen experience",
      "Suitable for restaurants and hotels",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Restaurants", description: "Suitable for commercial restaurant kitchen exhaust systems." },
      { title: "Hotels", description: "Used for kitchen ventilation and exhaust systems in hospitality facilities." },
      { title: "Commercial Kitchens", description: "Designed for large-scale kitchen exhaust requirements." },
      { title: "Food Processing Facilities", description: "Suitable for selected ventilation and exhaust applications." },
      { title: "Industrial Canteens", description: "Used for ventilation and removal of kitchen exhaust." },
    ],
    designFabrication:
      "Our kitchen exhaust ducting can be designed and fabricated according to approved drawings, airflow requirements, routing and site conditions.",
    supplyAcrossIndia:
      "We supply customized kitchen exhaust ducts across India for contractors, restaurants, hotels, commercial kitchens and industrial facilities.",
    faqs: [
      { question: "What is a Kitchen Exhaust Duct?", answer: "A Kitchen Exhaust Duct is a ducting system used to remove cooking fumes, smoke, heat, grease-laden air and vapours from kitchen areas through an exhaust system." },
      { question: "Can kitchen exhaust ducts be customized?", answer: "Yes. Dimensions, material, thickness and configuration can be customized according to project requirements." },
      { question: "Where are kitchen exhaust ducts used?", answer: "They are used in restaurants, hotels, commercial kitchens, food facilities and industrial canteens." },
    ],
    manufacturingProcess: [
      "Airflow and routing review against drawings",
      "Material and thickness selection",
      "Cutting and forming to required dimensions",
      "Jointing and access provision",
      "Inspection and finishing",
      "Marking and dispatch",
    ],
    installationInformation: [
      "Routed and supported as per approved drawings",
      "Jointing arrangement appropriate to the exhaust duty",
      "Access provision where maintenance is required",
      "Coordination with hood and fan equipment",
    ],
    maintenanceInformation: [
      "Regular cleaning schedule appropriate to kitchen usage",
      "Inspection of joints and internal surfaces",
      "Checking of access openings",
      "External finish upkeep",
    ],
    industries: ["Hospitality", "Commercial", "Food Processing", "Industrial"],
  },
];
