import type { ProductContent } from "./types";

export const PRODUCTS_PART2: ProductContent[] = [
  {
    slug: "fire-rated-duct",
    name: "Fire Rated Duct",
    h1: "Fire Rated Duct Manufacturer & Supplier in Mumbai, India",
    category: "Product",
    primaryKeyword: "Fire Rated Duct",
    secondaryKeywords: [
      "Fire Rated Duct Manufacturer in Mumbai",
      "fire resistant ducting",
      "smoke control duct",
      "HVAC fire protection duct",
    ],
    seoTags: [
      "Fire Rated Duct", "Fire Resistant Ducting", "Smoke Control Duct",
      "Fire Rated HVAC Duct", "Duct Manufacturer Mumbai", "Fire Protection Duct",
      "Duct Fabrication India", "Commercial Fire Duct", "Ventilation Duct",
    ],
    seoTitle: "Fire Rated Duct Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS fabricates Fire Rated Ducts according to approved specifications and fire-rated system requirements. Project-specific supply across India. Get a quotation.",
    seoKeywords:
      "fire rated duct, fire resistant ducting manufacturer Mumbai, smoke control duct, fire rated HVAC duct India",
    shortDescription:
      "Our **Fire Rated Ducts** are specialized ducting solutions designed for HVAC and ventilation applications where fire-resistance requirements are specified by the project. As a **Fire Rated Duct Manufacturer and Supplier in Mumbai**, we provide project-specific fabrication and fire-rated ducting solutions according to approved specifications.\n\nFire-rated duct systems are selected and constructed according to the required fire rating, system design, building requirements and applicable project standards.",
    manufacturingNarrative:
      "### Fire Rated Duct Manufacturing\n\nOur fire-rated ducting solutions can be configured according to approved drawings and project specifications. Construction, coating, insulation, reinforcement and jointing arrangements depend on the required fire-resistance system.",
    material: "Selected as specified for the approved fire-rated duct system and project requirement.",
    technicalSpecifications: [
      { label: "Product", value: "Fire Rated Duct" },
      { label: "Construction", value: "As Per Approved Fire-Rated System" },
      { label: "Material", value: "As Specified" },
      { label: "Fire Rating", value: "As Per Project Requirement" },
      { label: "Coating / Protection", value: "Approved Fire-Rated System" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Jointing", value: "As Specified" },
      { label: "Fabrication", value: "Approved Drawings" },
      { label: "Application", value: "HVAC / Smoke Control / Fire Safety" },
      { label: "Supply", value: "Pan India" },
    ],
    features: [
      "Fire-rated ducting solutions",
      "Project-specific fire protection",
      "Customized dimensions",
      "Drawing-based fabrication",
      "Suitable for specified fire safety applications",
      "Suitable for HVAC and ventilation systems",
      "Compatible with approved fire-rated systems",
      "Professional fabrication",
      "Pan-India supply",
    ],
    benefits: [
      "Project-specific fire-rated solutions",
      "Drawing-based fabrication",
      "Customized configurations",
      "HVAC and smoke-control applications",
      "Commercial and industrial applications",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Commercial Buildings", description: "Used where HVAC and ventilation ductwork is required to meet specified fire-resistance criteria." },
      { title: "Hospitals", description: "Can be fabricated to suit healthcare project specifications and safety requirements." },
      { title: "Hotels", description: "Suitable for hospitality projects requiring fire-rated duct arrangements." },
      { title: "Industrial Facilities", description: "Used in industrial buildings where fire-rated duct systems are specified." },
      { title: "Shopping Malls", description: "Suitable for large commercial developments with fire and smoke control requirements." },
      { title: "Infrastructure Projects", description: "Fabricated to suit project-specific fire safety and HVAC requirements." },
      { title: "Fire & Smoke Control Systems", description: "Used in smoke extract and pressurisation ductwork where rated construction is specified." },
      { title: "HVAC Installations", description: "Applied where HVAC ducting requires specified fire protection." },
    ],
    designFabrication:
      "Our fire-rated ducting is fabricated according to approved drawings and the specified fire-rated system. Material, protection system, insulation, thickness and fire rating are selected according to project requirements.",
    supplyAcrossIndia:
      "We support HVAC contractors, consultants, EPC companies and project developers with customized fire-rated ducting solutions across India.",
    faqs: [
      { question: "What is a Fire Rated Duct?", answer: "A Fire Rated Duct is a specially protected HVAC or ventilation duct system designed to maintain its required performance for a specified period under fire conditions." },
      { question: "Is the fire rating customizable?", answer: "The required fire rating depends on the building, application and approved fire-rated system. We fabricate according to project specifications." },
      { question: "Where are fire-rated ducts used?", answer: "They are used in buildings and facilities where HVAC, ventilation or smoke-control ductwork requires specified fire resistance." },
    ],
    manufacturingProcess: [
      "Review of approved fire-rated system and drawings",
      "Duct fabrication to specified construction",
      "Application of the specified protection system",
      "Reinforcement and joint arrangement",
      "Inspection and verification against specification",
      "Protection, marking and dispatch",
    ],
    installationInformation: [
      "Installation to follow the approved fire-rated system requirements",
      "Joint and penetration details as specified",
      "Support arrangement per the system design",
      "Coordination with fire-stopping and building services",
    ],
    maintenanceInformation: [
      "Inspection of protection system condition",
      "Repair of damaged protection as specified",
      "Periodic checks at access locations",
      "Record-keeping of maintenance activity",
    ],
    industries: ["Commercial", "Healthcare", "Hospitality", "Industrial", "Infrastructure"],
  },

  {
    slug: "volume-control-damper",
    name: "Volume Control Damper",
    h1: "Volume Control Damper Manufacturer & Supplier in Mumbai, India",
    category: "Accessories Part",
    primaryKeyword: "Volume Control Damper",
    secondaryKeywords: [
      "Volume Control Damper Manufacturer in Mumbai",
      "HVAC airflow damper",
      "VCD duct damper",
      "air balancing damper",
    ],
    seoTags: [
      "Volume Control Damper", "VCD", "HVAC Damper", "Airflow Control Damper",
      "Duct Damper Manufacturer", "HVAC Accessories Mumbai", "Air Balancing",
      "Ventilation Damper", "Ducting Accessories India",
    ],
    seoTitle: "Volume Control Damper Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures Volume Control Dampers for HVAC airflow regulation and air balancing. Customized duct-mounted dampers with pan-India supply.",
    seoKeywords:
      "volume control damper, VCD manufacturer Mumbai, HVAC airflow damper, duct mounted damper India, air balancing damper",
    shortDescription:
      "Our **Volume Control Dampers** are HVAC air-control components designed to regulate and balance airflow within ducting systems. As a **Volume Control Damper Manufacturer in Mumbai**, we manufacture and supply dampers for commercial, industrial and institutional HVAC applications.",
    manufacturingNarrative:
      "### Precision Volume Control Damper Manufacturing\n\nOur dampers are manufactured according to required duct dimensions and project specifications. Blade configuration, frame construction, operating mechanism and dimensions can be customized according to application requirements.",
    material: "Fabricated to suit duct construction and project requirement.",
    technicalSpecifications: [
      { label: "Product", value: "Volume Control Damper" },
      { label: "Application", value: "HVAC Airflow Control" },
      { label: "Construction", value: "As Per Requirement" },
      { label: "Blade Type", value: "As Specified" },
      { label: "Frame", value: "As Required" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Operation", value: "Manual / As Specified" },
      { label: "Installation", value: "Duct Mounted" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Airflow regulation",
      "Customized sizes",
      "Duct-mounted design",
      "Suitable for HVAC systems",
      "Suitable for air balancing",
      "Project-specific fabrication",
      "Easy integration with ductwork",
      "Commercial and industrial applications",
    ],
    benefits: [
      "Customized dimensions",
      "HVAC-specific fabrication",
      "Suitable for airflow control",
      "Project-based manufacturing",
      "Commercial and industrial applications",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "HVAC Air Distribution", description: "Used to regulate airflow within supply and return air duct systems." },
      { title: "Commercial Buildings", description: "Installed in HVAC systems across offices, commercial complexes and institutions." },
      { title: "Industrial Plants", description: "Used for airflow control in industrial ventilation and air-handling systems." },
      { title: "Hospitals", description: "Can be provided to suit project-specific HVAC requirements in healthcare facilities." },
      { title: "Hotels", description: "Used in hospitality HVAC systems for air balancing and zone control." },
      { title: "Offices", description: "Suitable for regulating air distribution in office HVAC systems." },
      { title: "Shopping Malls", description: "Used across large commercial air-distribution networks." },
      { title: "Institutional Buildings", description: "Suitable for HVAC installations in institutional and public buildings." },
    ],
    designFabrication:
      "Our VCDs can be manufactured according to duct dimensions and approved HVAC drawings, ensuring compatibility with the associated duct system.",
    supplyAcrossIndia:
      "We supply **Volume Control Dampers across India** for HVAC contractors, consultants, EPC companies and industrial customers.",
    faqs: [
      { question: "What is a Volume Control Damper?", answer: "A Volume Control Damper is an HVAC component used to regulate airflow through a duct section." },
      { question: "Where are VCDs used?", answer: "They are used in HVAC and ventilation systems to help regulate and balance air distribution." },
      { question: "Can the damper size be customized?", answer: "Yes. Damper dimensions can be manufactured according to the connected duct size and project requirements." },
    ],
    manufacturingProcess: [
      "Duct size and requirement confirmation",
      "Frame and blade fabrication",
      "Operating mechanism assembly",
      "Fitting and movement verification",
      "Finishing and inspection",
      "Marking and dispatch",
    ],
    installationInformation: [
      "Mounted at accessible locations within the duct run",
      "Orientation as indicated on the drawings",
      "Clearance provided for operating mechanism",
      "Balancing carried out by the commissioning team",
    ],
    maintenanceInformation: [
      "Periodic operation check to confirm free movement",
      "Inspection of blade and frame condition",
      "Lubrication of moving parts where applicable",
      "Re-adjustment during system rebalancing",
    ],
    industries: ["Commercial", "Industrial", "Healthcare", "Hospitality", "Infrastructure"],
  },

  {
    slug: "duct-flange",
    name: "Duct Flange & Fittings",
    h1: "Duct Flange & Fittings Manufacturer & Supplier in Mumbai, India",
    category: "Accessories Part",
    primaryKeyword: "Duct Flange & Fittings",
    secondaryKeywords: [
      "Duct Flange Manufacturer in Mumbai",
      "HVAC duct fittings",
      "duct connectors",
      "duct accessories supplier",
    ],
    seoTags: [
      "Duct Flange", "Duct Fittings", "HVAC Duct Accessories", "Duct Connectors",
      "Flange Manufacturer Mumbai", "Duct Installation", "Ducting Accessories India",
      "Commercial Ducting", "Industrial Ventilation",
    ],
    seoTitle: "Duct Flange & Fittings Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures Duct Flanges and Fittings for HVAC duct assembly and installation. Customized MS and SS components with drawing-based supply across India.",
    seoKeywords:
      "duct flange and fittings, HVAC duct accessories, duct connector manufacturer Mumbai, duct fittings supplier India",
    shortDescription:
      "Our **Duct Flanges and Fittings** are HVAC duct accessories designed to support duct assembly, connection and installation. As a **Duct Flange and Fittings Manufacturer in Mumbai**, we provide customized components for commercial, industrial and infrastructure HVAC projects.",
    manufacturingNarrative:
      "### Precision Duct Flange & Fittings Manufacturing\n\nOur duct accessories are fabricated according to duct dimensions, jointing requirements and approved project drawings. Different configurations can be produced according to the selected duct construction and installation method.",
    material: "Mild steel or stainless steel as required, in the thickness appropriate to the duct construction.",
    technicalSpecifications: [
      { label: "Product", value: "Duct Flanges & Fittings" },
      { label: "Material", value: "MS / SS as Required" },
      { label: "Type", value: "Flanges / Connectors / Fittings" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Thickness", value: "As Per Requirement" },
      { label: "Application", value: "HVAC Duct Installation" },
      { label: "Fabrication", value: "Drawing-Based" },
      { label: "Jointing", value: "As Specified" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Precision-fabricated components",
      "Suitable for HVAC duct installation",
      "Customized dimensions",
      "MS and SS options",
      "Drawing-based production",
      "Suitable for various duct configurations",
      "Commercial and industrial applications",
      "Project-specific manufacturing",
    ],
    benefits: [
      "Customized fabrication",
      "Accurate dimensions",
      "MS and SS options",
      "Drawing-based production",
      "HVAC-specific applications",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "Rectangular Duct Systems", description: "Used for joining and securing rectangular duct sections during installation." },
      { title: "Industrial HVAC", description: "Suitable for ducting assemblies in industrial air-handling and ventilation systems." },
      { title: "Commercial HVAC", description: "Used across commercial ducting installations and air-distribution networks." },
      { title: "Ventilation Systems", description: "Components fabricated to suit general ventilation duct arrangements." },
      { title: "Exhaust Systems", description: "Suitable for exhaust duct assemblies where secure connection is required." },
      { title: "Large Infrastructure Projects", description: "Supplied for ducting installations in large infrastructure developments." },
      { title: "Duct Installation & Maintenance", description: "Used during new installation, extension and maintenance of duct systems." },
    ],
    designFabrication:
      "Our duct flanges and fittings are manufactured according to the duct dimensions, connection requirements and approved project specifications.",
    supplyAcrossIndia:
      "We provide **Duct Flanges and Fittings across India** for HVAC contractors, fabricators, EPC companies and industrial customers.",
    faqs: [
      { question: "What are duct flanges?", answer: "Duct flanges are connection components used to join and secure duct sections during HVAC installation." },
      { question: "Can duct fittings be customized?", answer: "Yes. Flanges and fittings can be fabricated according to duct dimensions and project requirements." },
      { question: "Where are duct flanges and fittings used?", answer: "They are used across commercial HVAC, industrial ventilation, exhaust and infrastructure ducting systems." },
    ],
    manufacturingProcess: [
      "Duct dimension and jointing requirement review",
      "Component cutting and forming",
      "Flange and connector preparation",
      "Dimensional verification",
      "Finishing and surface protection",
      "Bundling, marking and dispatch",
    ],
    installationInformation: [
      "Components matched to duct section dimensions",
      "Installation as per the selected jointing arrangement",
      "Fastening and sealing as specified",
      "Compatibility with the duct construction confirmed",
    ],
    maintenanceInformation: [
      "Inspection of connections during duct maintenance",
      "Replacement of damaged components as required",
      "Re-tightening of accessible fasteners",
      "Surface protection upkeep",
    ],
    industries: ["Commercial", "Industrial", "Infrastructure", "Logistics"],
  },

  {
    slug: "access-door",
    name: "Duct Access Door",
    h1: "Duct Access Door Manufacturer & Supplier in Mumbai, India",
    category: "Accessories Part",
    primaryKeyword: "Duct Access Door",
    secondaryKeywords: [
      "Duct Access Door Manufacturer in Mumbai",
      "HVAC duct inspection door",
      "duct maintenance access",
      "duct access panel",
    ],
    seoTags: [
      "Duct Access Door", "Duct Access Panel", "HVAC Duct Accessories",
      "Duct Maintenance", "Access Door Manufacturer Mumbai", "Duct Inspection",
      "Ducting Accessories India", "Ventilation Duct Access", "Commercial Ducting",
    ],
    seoTitle: "Duct Access Door Manufacturer & Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS manufactures Duct Access Doors for HVAC duct inspection, cleaning and maintenance. Customized MS and SS access doors with pan-India supply.",
    seoKeywords:
      "duct access door, HVAC duct access panel, duct maintenance door manufacturer Mumbai, duct inspection access India",
    shortDescription:
      "Our **Duct Access Doors** are HVAC access components designed to provide convenient access to duct interiors for inspection, cleaning, maintenance and servicing. As a **Duct Access Door Manufacturer in Mumbai**, we manufacture and supply customized access doors for commercial and industrial ducting systems.",
    manufacturingNarrative:
      "### Precision Duct Access Door Manufacturing\n\nAccess doors are fabricated according to duct dimensions, installation location and project requirements. Size, frame configuration, locking arrangement and construction can be customized according to the application.",
    material: "Mild steel or stainless steel as required for the duct construction and application.",
    technicalSpecifications: [
      { label: "Product", value: "Duct Access Door" },
      { label: "Material", value: "MS / SS as Required" },
      { label: "Application", value: "HVAC Duct Inspection & Maintenance" },
      { label: "Size", value: "Standard & Custom" },
      { label: "Frame", value: "As Required" },
      { label: "Locking", value: "As Specified" },
      { label: "Construction", value: "As Per Project Requirement" },
      { label: "Installation", value: "Duct Mounted" },
      { label: "Supply", value: "Pan India" },
      { label: "Customization", value: "Available" },
    ],
    features: [
      "Easy duct access",
      "Suitable for inspection and maintenance",
      "Customized dimensions",
      "MS and SS construction options",
      "Secure door arrangement",
      "Suitable for HVAC systems",
      "Easy integration with ductwork",
      "Commercial and industrial applications",
    ],
    benefits: [
      "Customized sizes",
      "MS and SS options",
      "HVAC-specific fabrication",
      "Maintenance-friendly design",
      "Drawing-based manufacturing",
      "Pan-India supply",
    ],
    applicationDetails: [
      { title: "HVAC Duct Inspection", description: "Provides access for routine inspection of duct interiors and internal condition." },
      { title: "Duct Cleaning", description: "Allows cleaning access at selected points within the duct system." },
      { title: "Maintenance Access", description: "Enables servicing and maintenance of internal duct components." },
      { title: "Industrial Ventilation", description: "Used in industrial ventilation ductwork where regular access is required." },
      { title: "Commercial HVAC", description: "Installed across commercial ducting systems for ongoing maintenance." },
      { title: "Kitchen Exhaust Systems", description: "Suitable for exhaust ducts requiring periodic cleaning access." },
      { title: "Air Distribution Systems", description: "Used in supply and return air duct systems for inspection access." },
    ],
    designFabrication:
      "Access doors can be fabricated according to duct size, location, maintenance requirements and approved project drawings.",
    supplyAcrossIndia:
      "We manufacture and supply **Duct Access Doors across India** for HVAC contractors, industrial clients and commercial projects.",
    faqs: [
      { question: "What is a Duct Access Door?", answer: "A Duct Access Door provides an opening in ductwork for inspection, cleaning, maintenance and servicing." },
      { question: "Where are access doors installed?", answer: "They can be installed at selected locations in HVAC, ventilation and exhaust duct systems where maintenance access is required." },
      { question: "Can access doors be customized?", answer: "Yes. Dimensions and construction can be customized according to duct size and project requirements." },
    ],
    manufacturingProcess: [
      "Duct size and access requirement review",
      "Frame and door fabrication",
      "Locking arrangement assembly",
      "Fit and sealing verification",
      "Finishing and inspection",
      "Marking and dispatch",
    ],
    installationInformation: [
      "Positioned at locations indicated on the drawings",
      "Installed to allow clear access for maintenance",
      "Sealed to maintain duct integrity",
      "Orientation suited to the access requirement",
    ],
    maintenanceInformation: [
      "Regular checking of door seal condition",
      "Operation of locking arrangement",
      "Replacement of worn gaskets where applicable",
      "Cleaning around access openings",
    ],
    industries: ["Commercial", "Industrial", "Hospitality", "Healthcare"],
  },

  {
    slug: "cisbond-fr-802-coating",
    name: "CISBOND-FR 802 Fire Coating",
    h1: "CISBOND-FR 802 Fire Coating Supplier in Mumbai, India",
    category: "Fire Rated Coating",
    primaryKeyword: "CISBOND-FR 802 Fire Coating",
    secondaryKeywords: [
      "CISBOND-FR 802 Supplier in Mumbai",
      "fire protection coating",
      "fire rated coating for ducts",
      "HVAC fire coating",
    ],
    seoTags: [
      "CISBOND-FR 802", "Fire Protection Coating", "Fire Rated Coating",
      "HVAC Fire Coating", "Duct Fire Protection", "Fire Coating Mumbai",
      "Fire Safety Coating India", "Duct Coating", "Fire Rated Duct System",
    ],
    seoTitle: "CISBOND-FR 802 Fire Coating Supplier in Mumbai | MSNSS",
    seoDescription:
      "MSNSS supplies CISBOND-FR 802 Fire Coating for fire-protection and HVAC applications. Project-oriented supply and application support across India.",
    seoKeywords:
      "CISBOND-FR 802, fire protection coating, fire rated coating for ducts, HVAC fire coating Mumbai, fire coating supplier India",
    shortDescription:
      "**CISBOND-FR 802 Fire Coating** is a fire-protection coating solution used for applications where enhanced fire resistance is required. As a **CISBOND-FR 802 Fire Coating Supplier in Mumbai**, we provide product supply and project-oriented support according to specified application requirements.\n\nThe coating system should be selected, prepared and applied according to the manufacturer's technical documentation, approved project specifications and applicable fire-safety requirements.",
    manufacturingNarrative:
      "### CISBOND-FR 802 Fire Coating Application\n\nProper surface preparation and application are important for achieving the required performance of any fire-rated coating system. Application parameters such as surface condition, coating thickness, preparation method and curing requirements should follow the applicable product and project specifications.",
    material: "Fire-protection coating system, selected and applied to the approved project specification.",
    technicalSpecifications: [
      { label: "Product", value: "CISBOND-FR 802 Fire Coating" },
      { label: "Product Type", value: "Fire Protection Coating" },
      { label: "Application", value: "As Per Approved System" },
      { label: "Substrate", value: "As Specified" },
      { label: "Coating Thickness", value: "As Per Requirement" },
      { label: "Surface Preparation", value: "As Per Manufacturer Specification" },
      { label: "Application Method", value: "As Recommended" },
      { label: "Fire Performance", value: "As Per Applicable Test / Certification" },
      { label: "Supply", value: "Pan India" },
      { label: "Project Support", value: "Project Specific" },
    ],
    features: [
      "Fire-protection coating solution",
      "Suitable for specified fire-rated applications",
      "Project-specific application",
      "Professional coating support",
      "Suitable for selected HVAC duct applications",
      "Application according to technical requirements",
      "Available for projects across India",
    ],
    benefits: [
      "Project-oriented supply",
      "Fire-protection application",
      "Technical specification-based use",
      "Suitable for specified HVAC applications",
      "Pan-India availability",
    ],
    applicationDetails: [
      { title: "Fire-Rated HVAC Duct Systems", description: "Used where HVAC ductwork forms part of a specified fire-protection arrangement." },
      { title: "Fire Protection Applications", description: "Applied where enhanced fire resistance is required by the project specification." },
      { title: "Commercial Buildings", description: "Considered for fire-protection requirements in commercial developments." },
      { title: "Industrial Facilities", description: "Used in industrial buildings where fire-rated protection is specified." },
      { title: "Infrastructure Projects", description: "Supplied for infrastructure developments with fire-safety requirements." },
      { title: "HVAC Installations", description: "Applied to HVAC installations requiring fire protection as part of the approved system." },
    ],
    designFabrication:
      "The coating application should follow the relevant technical data, approved specifications and required fire-rating system. Surface preparation, application thickness and curing must be controlled according to the applicable requirements.",
    supplyAcrossIndia:
      "We provide **CISBOND-FR 802 Fire Coating supply across India** for suitable HVAC and fire-protection projects.",
    faqs: [
      { question: "What is CISBOND-FR 802?", answer: "CISBOND-FR 802 is a fire-protection coating product used for applications requiring specified fire-resistant performance." },
      { question: "Can it be used on HVAC ducts?", answer: "It may be used for suitable HVAC fire-rated duct applications when specified and approved as part of the required fire-protection system." },
      { question: "How should the coating be applied?", answer: "Application should follow the manufacturer's technical documentation and the approved project specification, including surface preparation and required coating thickness." },
    ],
    manufacturingProcess: [
      "Review of approved fire-protection specification",
      "Surface preparation as required",
      "Coating application to specified thickness",
      "Curing and coverage verification",
      "Inspection against project requirements",
      "Documentation and handover support",
    ],
    installationInformation: [
      "Applied by suitably prepared applicators",
      "Surface condition confirmed before application",
      "Coating thickness monitored during application",
      "Work carried out to the approved method statement",
    ],
    maintenanceInformation: [
      "Periodic inspection of coated surfaces",
      "Repair of damaged coating as specified",
      "Records of inspection and maintenance retained",
      "Re-application only to the approved specification",
    ],
    industries: ["Commercial", "Industrial", "Infrastructure", "Healthcare"],
  },

  {
    slug: "plasma-cutting-machine",
    name: "Plasma Cutting Machine",
    h1: "Plasma Cutting Machine for HVAC Duct Manufacturing in Mumbai, India",
    category: "Plant and Machinery",
    primaryKeyword: "Plasma Cutting Machine",
    secondaryKeywords: [
      "plasma cutting in HVAC manufacturing",
      "CNC sheet metal cutting",
      "duct panel cutting",
      "HVAC fabrication machinery",
    ],
    seoTags: [
      "Plasma Cutting Machine", "CNC Plasma Cutting", "Sheet Metal Cutting",
      "HVAC Duct Manufacturing", "Duct Fabrication", "Precision Cutting Mumbai",
      "Duct Panel Cutting", "Manufacturing Capability", "HVAC Fabrication India",
    ],
    seoTitle: "Plasma Cutting Machine for HVAC Duct Manufacturing in Mumbai | MSNSS",
    seoDescription:
      "See how our Plasma Cutting Machine supports accurate sheet-metal cutting for HVAC duct manufacturing. Precision component production from approved drawings.",
    seoKeywords:
      "plasma cutting machine, HVAC duct manufacturing, CNC plasma cutting Mumbai, sheet metal cutting for ducts, duct fabrication India",
    shortDescription:
      "Our **Plasma Cutting Machine** is used for accurate and efficient sheet-metal cutting during HVAC duct manufacturing and fabrication. As an HVAC duct manufacturing facility, we use precision cutting processes to produce components according to approved drawings and required dimensions.\n\nPlasma cutting supports efficient processing of sheet-metal components used in duct panels, fittings and other fabricated HVAC components.",
    manufacturingNarrative:
      "### Precision Sheet Metal Cutting\n\nThe cutting process can be carried out according to CAD drawings and required component dimensions. Accurate cutting helps maintain consistency during subsequent bending, forming and assembly operations.",
    material: "Processes sheet-metal stock used in HVAC duct fabrication, as supported by the machine capability.",
    technicalSpecifications: [
      { label: "Machine", value: "Plasma Cutting Machine" },
      { label: "Application", value: "Sheet Metal Cutting" },
      { label: "Industry", value: "HVAC Duct Manufacturing" },
      { label: "Material", value: "As Supported by Machine" },
      { label: "Cutting", value: "CNC / Plasma Process" },
      { label: "Input", value: "CAD / Drawing Based" },
      { label: "Output", value: "Duct Panels & Components" },
      { label: "Production", value: "Project Based" },
      { label: "Accuracy", value: "As Per Machine Capability" },
      { label: "Customization", value: "Drawing Based" },
    ],
    features: [
      "Precision sheet-metal cutting",
      "Suitable for HVAC fabrication",
      "Drawing-based cutting",
      "Efficient component production",
      "Suitable for customized duct components",
      "Consistent cutting process",
      "Supports large-scale fabrication",
      "Suitable for industrial production",
    ],
    benefits: [
      "Accurate component dimensions",
      "Consistent fabrication",
      "Reduced manual cutting",
      "Better assembly fit",
      "Efficient production",
      "Suitable for customized designs",
    ],
    applicationDetails: [
      { title: "HVAC Duct Panels", description: "Used to cut sheet-metal panels that form the body of fabricated duct sections." },
      { title: "Sheet-Metal Components", description: "Produces a range of components used in duct assemblies and fittings." },
      { title: "Duct Fittings", description: "Supports fabrication of fittings requiring accurate cut profiles." },
      { title: "Industrial Fabrication", description: "Used across industrial sheet-metal fabrication carried out at our facility." },
      { title: "Ventilation Components", description: "Produces components used in ventilation duct systems." },
      { title: "Customized HVAC Parts", description: "Supports one-off and project-specific component production from drawings." },
    ],
    designFabrication:
      "Plasma cutting is integrated into the duct fabrication process to produce accurately dimensioned sheet-metal components before bending, forming and assembly.",
    supplyAcrossIndia:
      "Our fabrication process combines precision cutting with forming, joining and assembly operations to manufacture HVAC duct components according to approved project drawings.",
    faqs: [
      { question: "What is a Plasma Cutting Machine?", answer: "A plasma cutting machine uses a high-temperature plasma arc to cut electrically conductive materials into required shapes and dimensions." },
      { question: "How is plasma cutting used in HVAC?", answer: "It can be used to cut sheet-metal panels and components required for HVAC duct fabrication." },
      { question: "Can components be cut according to drawings?", answer: "Yes. Components can be produced based on suitable CAD drawings and manufacturing requirements." },
    ],
    manufacturingProcess: [
      "Drawing and component data preparation",
      "Material selection and setup",
      "CNC / plasma cutting to profile",
      "Component collection and identification",
      "Transfer to forming and assembly operations",
    ],
    installationInformation: [
      "Components produced to suit the fabrication sequence",
      "Identification maintained through subsequent operations",
    ],
    maintenanceInformation: [
      "Routine machine maintenance as per manufacturer guidance",
      "Consumable inspection and replacement",
      "Cutting quality checks during production",
    ],
    industries: ["Manufacturing", "Industrial", "Commercial"],
  },

  {
    slug: "bending-punching-machine",
    name: "Bending & Punching Machine",
    h1: "Bending & Punching Machine for HVAC Duct Manufacturing in Mumbai, India",
    category: "Plant and Machinery",
    primaryKeyword: "Bending & Punching Machine",
    secondaryKeywords: [
      "bending and punching in HVAC manufacturing",
      "sheet metal forming machine",
      "duct panel forming",
      "HVAC fabrication machinery",
    ],
    seoTags: [
      "Bending & Punching Machine", "Sheet Metal Forming", "Duct Panel Forming",
      "HVAC Duct Manufacturing", "Duct Fabrication", "Punching Machine Mumbai",
      "Metal Bending", "Manufacturing Capability", "HVAC Fabrication India",
    ],
    seoTitle: "Bending & Punching Machine for HVAC Duct Manufacturing in Mumbai | MSNSS",
    seoDescription:
      "See how our Bending & Punching Machine supports precision sheet-metal forming for HVAC duct manufacturing. Accurate duct panels from approved drawings.",
    seoKeywords:
      "bending and punching machine, HVAC duct manufacturing, sheet metal forming Mumbai, duct panel fabrication India",
    shortDescription:
      "Our **Bending & Punching Machine** supports precision sheet-metal forming and punching operations used in HVAC duct manufacturing. These processes help produce accurately formed duct panels, edges, holes and connection features according to approved drawings.",
    manufacturingNarrative:
      "### Precision Bending & Punching\n\nControlled bending and punching operations help achieve consistent dimensions and repeatable component fabrication. Machine settings and processes are selected according to material, thickness, component design and project requirements.",
    material: "Processes sheet-metal stock used in HVAC duct fabrication, as supported by the machine capability.",
    technicalSpecifications: [
      { label: "Machine", value: "Bending & Punching Machine" },
      { label: "Application", value: "HVAC Sheet Metal Fabrication" },
      { label: "Process", value: "Bending / Punching" },
      { label: "Material", value: "Sheet Metal as Supported" },
      { label: "Input", value: "Drawing / CAD Based" },
      { label: "Output", value: "Duct Panels & Components" },
      { label: "Production", value: "Project Based" },
      { label: "Accuracy", value: "As Per Machine Capability" },
      { label: "Configuration", value: "As Required" },
      { label: "Customization", value: "Drawing Based" },
    ],
    features: [
      "Precision sheet-metal bending",
      "Accurate punching operations",
      "Consistent component fabrication",
      "Suitable for HVAC duct manufacturing",
      "Drawing-based production",
      "Efficient manufacturing process",
      "Suitable for customized duct components",
      "Supports industrial-scale production",
    ],
    benefits: [
      "Precision fabrication",
      "Drawing-based production",
      "Consistent dimensions",
      "Efficient sheet-metal processing",
      "Customized components",
      "Suitable for commercial and industrial HVAC projects",
      "Project-oriented manufacturing",
    ],
    applicationDetails: [
      { title: "HVAC Duct Panels", description: "Used for forming sheet-metal panels used in duct manufacturing." },
      { title: "Duct Fittings", description: "Supports fabrication of components and fittings requiring accurate bends and punched features." },
      { title: "Flanges & Connections", description: "Can support production of components requiring accurately positioned holes and formed edges." },
      { title: "Sheet Metal Fabrication", description: "Suitable for various industrial sheet-metal manufacturing operations." },
    ],
    designFabrication:
      "Bending and punching are important stages in HVAC duct fabrication. After cutting, sheet-metal components can be formed and punched according to the required design before assembly and joining.",
    supplyAcrossIndia:
      "Our manufacturing process combines **cutting, bending, punching, forming and assembly** to produce HVAC duct components according to project drawings and specifications.",
    faqs: [
      { question: "What is a Bending & Punching Machine?", answer: "It is industrial sheet-metal machinery used to form bends and create accurately positioned holes or punched features in metal components." },
      { question: "How is it used in HVAC duct manufacturing?", answer: "It is used to form duct panels, edges, flanges, connections and other sheet-metal components required for HVAC duct fabrication." },
      { question: "Can components be manufactured according to drawings?", answer: "Yes. Components can be processed according to suitable CAD drawings and approved manufacturing dimensions." },
    ],
    manufacturingProcess: [
      "Drawing and component requirement review",
      "Machine setup for material and thickness",
      "Bending and forming to required profile",
      "Punching of holes and connection features",
      "Dimensional verification",
      "Transfer to assembly operations",
    ],
    installationInformation: [
      "Formed components prepared for the assembly sequence",
      "Features positioned to suit the duct design",
    ],
    maintenanceInformation: [
      "Routine machine maintenance per manufacturer guidance",
      "Tooling inspection and replacement",
      "Dimensional checks during production",
    ],
    industries: ["Manufacturing", "Industrial", "Commercial", "Infrastructure"],
  },
];
